kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: golang:1.19
    commands:
      - echo build

  - name: test
    image: golang:1.19
    commands:
      - echo test

  - name: deploy
    image: golang:1.19
    commands:
      - echo deploy
